-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Create profiles table (extends auth.users)
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  full_name text,
  phone text,
  role text default 'user',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for profiles
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on profiles
  for update using (auth.uid() = id);

-- Trigger to create profile on signup
create function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, role)
  values (new.id, new.raw_user_meta_data->>'full_name', 'user');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();


-- Create stations table
create table stations (
  id bigint generated by default as identity primary key,
  name text not null,
  code text not null unique,
  city text not null,
  address text,
  latitude double precision,
  longitude double precision,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create trains table
create table trains (
  id bigint generated by default as identity primary key,
  train_number text not null unique,
  type text not null, -- 'express', 'local', etc.
  status text default 'active',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create carriage_types table
create table carriage_types (
  id bigint generated by default as identity primary key,
  name text not null,
  capacity int,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create carriages table
create table carriages (
  id bigint generated by default as identity primary key,
  carriage_number text not null,
  carriage_type_id bigint references carriage_types(id),
  model text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create trips table
create table trips (
  id bigint generated by default as identity primary key,
  train_id bigint references trains(id),
  origin_station_id bigint references stations(id),
  destination_station_id bigint references stations(id),
  departure date, -- Stores the date part
  departure_time timestamp with time zone not null,
  arrival_time timestamp with time zone not null,
  first_class_price numeric(10,2) default 0,
  second_class_price numeric(10,2) default 0,
  economic_price numeric(10,2) default 0,
  quantities int default 0, -- Total seats?
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create trip_departures table (if used for specific date instances, though trips table seems to have specific dates)
-- Based on code, trip_departures might be sub-instances or simplified versions.
create table trip_departures (
  id bigint generated by default as identity primary key,
  trip_id bigint references trips(id) on delete cascade,
  departure_time timestamp with time zone,
  arrival_time timestamp with time zone,
  available_seats int,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create reservations table
create table reservations (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id),
  trip_id bigint references trips(id),
  seat_class text,
  number_of_seats int,
  status text default 'pending', -- pending, confirmed, cancelled
  booking_reference text,
  total_price numeric(10,2),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS (Basic setup - strictly allowing public read for demo purposes, restrict writes in production)
alter table stations enable row level security;
create policy "Stations are viewable by everyone" on stations for select using (true);
create policy "Admins can insert stations" on stations for insert with check (exists (select 1 from profiles where id = auth.uid() and role = 'admin'));
create policy "Admins can update stations" on stations for update using (exists (select 1 from profiles where id = auth.uid() and role = 'admin'));

alter table trains enable row level security;
create policy "Trains are viewable by everyone" on trains for select using (true);

alter table trips enable row level security;
create policy "Trips are viewable by everyone" on trips for select using (true);

alter table reservations enable row level security;
create policy "Users can view own reservations" on reservations for select using (auth.uid() = user_id);
create policy "Users can create reservations" on reservations for insert with check (auth.uid() = user_id);
create policy "Users can update own reservations" on reservations for update using (auth.uid() = user_id);

-- Insert some dummy data
insert into stations (name, code, city, address) values
('Cairo Station', 'CAI', 'Cairo', 'Ramses Square'),
('Alexandria Station', 'ALX', 'Alexandria', 'Misr Station'),
('Luxor Station', 'LXR', 'Luxor', 'El-Mahatta Square');

insert into trains (train_number, type) values
('TR-1001', 'Express'),
('TR-2002', 'VIP');

insert into trips (train_id, origin_station_id, destination_station_id, departure, departure_time, arrival_time, first_class_price, second_class_price, economic_price, quantities) values
(1, 1, 2, CURRENT_DATE, CURRENT_TIMESTAMP + interval '1 day', CURRENT_TIMESTAMP + interval '1 day 3 hours', 150.00, 100.00, 50.00, 200);

