-- Run this in your Supabase SQL Editor to create the missing table

create table if not exists trip_departures (
  id bigint generated by default as identity primary key,
  trip_id bigint references trip("Trip_ID") on delete cascade,
  departure_time timestamp with time zone,
  arrival_time timestamp with time zone,
  available_seats int,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table trip_departures enable row level security;

-- Policies
create policy "Trip Departures are viewable by everyone" on trip_departures for select using (true);
create policy "Admins can insert trip departures" on trip_departures for insert with check (true); -- Simplified for dev
create policy "Admins can update trip departures" on trip_departures for update using (true);
create policy "Admins can delete trip departures" on trip_departures for delete using (true);
